### ISSUE TITLE
 docker-compose up -d socr_db network reverse_proxy declared as external, but could not be found

### ISSUE THREAD

**Issue by gedw99** [sentriz/socr#20]
using docker-compose.yml copy.example

```
docker-compose up -d socr_db
network reverse_proxy declared as external, but could not be found
```

**Comment by sentriz** [comment]
closing for now, but let me about your reverse proxy setup if you have one . happy to help 👍

**Comment by gedw99** [comment]
I am using colima. It’s for Mac . 

It’s a replacement for docker desktop closed source software.
